language: php

php:
  - 5.4

mysql:
  database: dkan_travis
  username: root
  encoding: utf8

install:
  - cd test
  - composer install
  - mysql -e 'create database dkan_travis;'
  - sudo apt-get update > /dev/null
  - sudo apt-get --quiet=2 install php5-cgi php5-curl php5-gd php5-mysql > /dev/null

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:dev-master

before_script:
  # Install DKAN
  - cd ../..
  - mkdir drupal
  - cd drupal
  - cp $TRAVIS_BUILD_DIR/drupal-org-core.make ./
  - drush make --prepare-install drupal-org-core.make --yes
  - cp -R $TRAVIS_BUILD_DIR profiles/
  - cd profiles/dkan
  - drush -y make --no-core --contrib-destination=. drupal-org.make --no-recursion
  - drush si dkan --sites-subdir=default --db-url=mysql://root:@127.0.0.1/dkan_travis --account-name=admin --account-pass=admin  --site-name="DKAN" install_configure_form.update_status_module='array(FALSE,FALSE)' --yes
  - drush cc all --yes
  - drush --quiet --yes --root=$PWD --server=builtin runserver :8888 > /dev/null 2>&1 &
  - sleep 4s

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.35.0.jar
  - java -jar selenium-server-standalone-2.35.0.jar -quiet -p 4444 -log shut_up_selenium &
  - sleep 5
  - cd test

script:
  - bin/behat --profile travis features/groups.feature
  - bin/behat --profile travis features/dataset.feature
  - bin/behat --profile travis features/datastore.feature
  - bin/behat --profile travis features/editor.feature
  - bin/behat --profile travis features/home.feature
  - bin/behat --profile travis features/search.feature
  - bin/behat --profile travis features/recline.feature
